### ISSUE TITLE
Why is the minimap resized from 64x64 to 84x84?

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [tonybeltramelli/Supervised-End-to-end-Weight-sharing-for-StarCraft-II#1]
Hi Tony Beltramelli,

Me and some friends edited your project to make it work on the DefeatRoaches map and it works very well :)
However, we cannot figure out why the minimap feature layer is resized before being fed to the network. Do you still remember why you did that?

Thank you,
Raphaël

**Comment by tonybeltramelli** [comment]
Hi Raphael,

Thanks for your interest in this project. I am really happy to hear that it worked out of the box on the DefeatRoaches map! :) Please share a gif/video of the agent if you have one!

Good question and I have to admit not being entirely sure why I ended up upsampling the minimap feature layer. It was a hackathon-like coding experience with very little time available, perhaps training worked better with a 84x84 than a 64x64 feature map...

Have fun!
Tony

**Comment by RaphaelRoyerRivard** [comment]
Hi Tony,

We will certainly share a gif sooner or later.
I'm not sure if the upsampling was useful for the training but when it is not done, the output position seems off because the action are applied on a 84x84 map. We are now using the 84x84 screen_player_relative input layer instead of the 64x64 minimap_player_relative input layer so we are not tackling this problem anymore.
If you are interested by our developments on your project, subscribe to my fork ;)

Raphael

**Comment by tonybeltramelli** [comment]
Hi Raphael,

This is very interesting that the output position being sometimes off has been fixed by changing the size of the input map. It does not really make sense since the output position is learned through regression as a ratio from 0.0 to 1.0 instead of an absolute value. Therefore, this ratio is insensitive to the actual pixel dimension of the input map.
Great if you solve the problem though! :)
